# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Set Timestamp
        shell: bash
        run: |
          echo "TSTAMP=$(date -u +"%Y-%m-%d_%H%M%S")" >> $GITHUB_ENV

      - name: Run linter
        run: deno lint

      - name: Backup
        run: deno task backup --org TEIC

      - name: Convert to TEI CMC
        run: deno task convert 

      - name: Save and upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: TEIC_issues-${{ env.TSTAMP }}
          path: |
            ${{ github.workspace }}/issues
            ${{ github.workspace }}/tei


